# Assignment on Numpy Array Operations
### About Numpy and uses of some functions picked from the Numpy documentation

Numpy is a powerful python library used for numerical operations.
Numpy stands for 'Numerical Python'.

> - numpy.swapaxes
> - np.nanmean
> - np.nanmstd
> - np.nanvar
> - np.nanmedian

Let's begin by importing Numpy and listing out the functions covered in this notebook.

In [6]:
import numpy as np

# List of functions explained 
> function1 = `numpy.swapaxes()`

> function2 = `np.nanmean()`

> function3 = `np.nanmstd()`

> function4 = `nanvar()`

> function5 = `nanmedian()`

## Function 1 - np.swapaxes()

the `np.swapaxes` numpy function (like the name implies) is used to switch two axis in an array.
it has the syntax: `np.swapaxes(z, axis1, axis2)`

In [20]:
#Example 1
z = np.arange(9).reshape(3,3)
z

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [19]:
np.swapaxes(z, 1,0)

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

Here, Columns are just swapped to rows.

In [28]:
#Example 2
arr1 = [[1, 2, 7], 
        [3, 4., 8]]

arr2 = [[5, 6, 7], 
        [8, 9, 10]]
x = np.concatenate((arr1,arr2))
x


array([[ 1.,  2.,  7.],
       [ 3.,  4.,  8.],
       [ 5.,  6.,  7.],
       [ 8.,  9., 10.]])

In [30]:
np.swapaxes(x, 1, 0)

array([[ 1.,  3.,  5.,  8.],
       [ 2.,  4.,  6.,  9.],
       [ 7.,  8.,  7., 10.]])

Here, we can see that even the shape of x is changed from a `(4,3)` to a `(3,4)`, it's still the same with the previous example where columns were swapped with rows.

In [33]:
arr1 = [[1, 2], 
        [3, 4.]
    [5, 6, 7], 
        [8, 9, 10]]
np.swapaxes(arr1,1,0)

<>:2: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
<>:2: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
C:\Users\lenovo\AppData\Local\Temp\ipykernel_8872\3140304826.py:2: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
  [3, 4.]
C:\Users\lenovo\AppData\Local\Temp\ipykernel_8872\3140304826.py:2: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
  [3, 4.]
C:\Users\lenovo\AppData\Local\Temp\ipykernel_8872\3140304826.py:2: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
  [3, 4.]


TypeError: list indices must be integers or slices, not tuple

You can see that it throws a TypeError, because what we gave is looking like a tuple and we know from previous lectures that tuples cannot be modified, so solving this will be to convert the above to a list.

Some closing comments about when to use this function.

## Function 2 - np.nanmean()

This function `np.nanmean()` returns the mean of any given dataset even if it contains null values, i.e NAN.

In [57]:
#Example 1
a = np.array([[200, 20, 200]])
a

array([[200,  20, 200]])

In [58]:
np.nanmean(a)

140.0

The mean we can all agree on.

In [61]:
#Example 2
a = np.array([[200, 20, np.nan, 200]])
a.mean()

nan

In [60]:
np.nanmean(a)

140.0

Now we can see that with or without the `nan`, the mean remained the same with the `np.nanmean` function.

This is important when dealing large dataset

## Function 3 - np.nanstd()

This function calculates the standard deviation with or without the null values.

In [70]:
# Example 1 
a = np.array([[200, 20, 200]])
a.std()

84.8528137423857

In [72]:
np.nanstd(a)

84.8528137423857

The Standard deviation we can both agree on.

In [73]:
# Example 2
a = np.array([[200, 20, np.nan, 200]])
a.std()

nan

In [74]:
np.nanstd(a)

84.8528137423857

same with the `np.nanmean()` function, it completely ignores the `nan` and calculates the standard deviation of the data given.

## Function 4 - np.nanvar()

This function like the ones preceeding it, calculates the variance of any given dataset and ignores the `nan` given.

In [75]:
# Example 1 
a = np.array([[200, 20, 200]])
a.var()

7200.0

In [76]:
np.nanvar(a)

7200.0

The variance the whole world agrees on.

In [77]:
# Example 2
a = np.array([[200, 20, np.nan, 200]])
a.var()

nan

In [78]:
np.nanvar(a)

7200.0

Eureka!

## Function 5 - np.nanmedian()

The `np.nanmedian` function gives the median of a dataset that includes NAN, that is, it ignores the NAN values and gives the median of the remaining values.

In [85]:
# Example 1 
a = np.array([[200, 20, 200]])
np.median(a)

200.0

In [86]:
np.nanmedian(a)

200.0

In [87]:
# Example 2
a = np.array([[200, 20, np.nan, 200]])
np.median(a)

nan

In [88]:
np.nanmedian(a)

200.0

what the above example did is to ignore all the input values that are not numbers and returned the median value.

This is quite useful when dealing with a large amount of data that involves NAN, we can get the median of such dataset using the numpy `np.nanmedian` function.

## Conclusion

All that was computed here in this Notebook is just like the basics of all the array functions, and can come in handy when placed with basic challenges like the ones treated above.

## Reference Links
Provide links to your references and other interesting articles about Numpy arrays:
* Numpy official tutorial : https://numpy.org/doc/stable/user/quickstart.html
* Numpy API Reference : https://numpy.org/doc/stable/reference/index.html